### ISSUE TITLE
How to disable the fceux GUI when training Mario?

### ISSUE THREAD

**Issue by shinshiner** [pathak22/noreward-rl#10]
Hello, I think your idea is so cool, and I want to have a try by myself. However, when I train Mario, the fceux GUI will appear, which will slow down my training speed. Besides, I can not run my codes on server due to the fceux GUI. So I wonder how did you avoid this in your codes?

**Comment by pathak22** [comment]
You can install xvfb, `sudo apt-get install xvfb` and then run this command: 
`xvfb-run -s "-screen 0 1400x900x24" bash` and then run the code.

See here: https://github.com/openai/gym#rendering-on-a-server

**Comment by shinshiner** [comment]
Yes, I use this way by reading your 'README.md' and can run it on my server. But the speed is still low, Given a perfect path, mario needs 5 seconds to pass the level 1. Besides, when I reset the environment, it will open a new fceux and does not kill the old one, I will get more than 100 fceux after a few minutes, could you tell me how you solve this when training?

**Comment by pathak22** [comment]
@shinshiner how many a3c workers are you using? Yes, fceux simulator isn't super friendly to work with but it should not "hard" reset 100 times in few minutes. Something is wrong. You are using fceux in different xvfb screens, right?

**Comment by shinshiner** [comment]
I use 8-10 workers, and I have solved the fceux problem, but when I trained for about 4 hours, whatever message I send to env, it just did nothing and the whole processes were like 'down'.
