### ISSUE TITLE
Is this project also expected to work well on mujoco environment or not?

### ISSUE THREAD

**Issue by ghost** [pathak22/noreward-rl#11]
Hi,
I want to know whether this project is expected to work well on mujoco environment or not. This project is based on A3C which may not be suitable for mujoco?

**Comment by pathak22** [comment]
@fajlflal The project proposes just the ICM module -- it is agnostic to the RL algorithm it is used with. In our paper, we happened to use it with A3C. There are two ways to go about mujoco:
- make continuous variant of A3C (see supplementary material in Mnih etal), and put regression loss in ICM
- use regression ICM with TRPO or PPO

Any of these options should be fine.
