### ISSUE TITLE
The program seems to get stuck ?

### ISSUE THREAD

**Issue by shinshiner** [pathak22/noreward-rl#14]
Hello, Pathak. I tried to reproduce your codes in Mario env. But the program seems to get stuck: Mario does not act and the output just remains like this for about ten minutes :
```
balabala

Using universe head design
Using universe head design
Optimizer: ADAM with lr: 0.000100
Input observation shape:  (224, 256, 3)

Doing hard mario fceux reset (40 seconds wait) !
[2017-10-15 17:53:37,185] Starting training at gobal_step=0
```

I add some outputs in `a3c.py` and I find the program was stuck in 
`self.queue.put(next(rollout_provider), timeout=600.0)` (line 146)

Have you met similar problems ? Or it is just fine ? Could you tell me how to tackle it ?

**Comment by shinshiner** [comment]
When I terminate the threads, they post this error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/shin/noreward-rl/src/a3c.py", line 139, in run
    self._run()
  File "/home/shin/noreward-rl/src/a3c.py", line 151, in _run
    self.queue.put(next(rollout_provider), timeout=600.0)
  File "/home/shin/noreward-rl/src/a3c.py", line 178, in env_runner
    fetched = policy.act(last_state, *last_features)
  File "/home/shin/noreward-rl/src/model.py", line 224, in act
    {self.x: [ob], self.state_in[0]: c, self.state_in[1]: h})
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 943, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 188, 240, 3) for Tensor 'local/x:0', which has shape '(?, 224, 256, 3)'
```

It seems like there are some problems in the network architecture ?

**Comment by shinshiner** [comment]
Is this network architecture work for Mario ? Or I need to modify this architecture to fit Mario env ?

**Comment by shinshiner** [comment]
Oh, I made a mistake. I can run the code in my PC after I set some parameters. But the code will be stuck in `env.reset()` when running in my remote server, even with `xvfb-run`. But my simple a3c code can perfectly run, so I get confused. Any help would be great appreciated .

**Comment by pathak22** [comment]
You would need individual xvfb per worker and hence multiple xvfb runs per machine simultaneously.  This is how to do that: http://stackoverflow.com/a/30336424

**Comment by shinshiner** [comment]
Sorry for the delay, I just used one worker when I was debugging and suffered from this problem, I think I can connect a screen to my server to tackle this issue. Thanks for your kindly help ! :)
