### ISSUE TITLE
Model modification

### ISSUE THREAD

**Issue by ProgmasterX** [pathak22/noreward-rl#16]
In order to use it I need to download PRE-TRAINED models using your bash script. How do I edit model definition (layers, convolution stride, input and output shape, action space size)? How do I train the model from scratch?

P.S. I'm sorry for posting it here because you have no emails specified.

Looking forward to your reply.

**Comment by pathak22** [comment]
Pre-trained models are only needed to run demo (not for training from scratch etc.). You can modify the files and train the models as you want. The ReadMe contains all the information here: https://github.com/pathak22/noreward-rl#1-installation-and-usage
