### ISSUE TITLE
Can it work for robotic with continuous action space?

### ISSUE THREAD

**Issue by wonchul-kim** [pathak22/noreward-rl#17]
Hi, I am 2nd year of graduate student at Seoul National university, Seoul, Korea.
I am studying RL and want to apply your idea to make a contribution for controlling a robot.
I am just curious the possibility of applying it with DDPG, so it can work for robotics with continuous action space.

I am considering two area of robotics: one is manipulator which has task with sparse reward and another is a navigation.

How do you think? 
If you don't mind, I want to have your advise.

**Comment by pathak22** [comment]
Yes, it should work fine. We actually combined it with TRPO internally for continuous and got encouraging results.

For more details, see #11
