### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by manacoa** [pathak22/noreward-rl#4]
Hi Deepak,

The paper is great. Any chance of getting access to the training code?

Thanks!

Simon

**Comment by pathak22** [comment]
Yes, I have finally released the full training code. This comes with the scripts to train on VizDoom and Super Mario Bros., scripts to do inference and scripts to customize VizDoom environment for RL experiments. The wrappers which allow for faster training in Mario and Doom have also been released. :)
