### ISSUE TITLE
Performance of A3C on benchmark

### ISSUE THREAD

**Issue by chingyaoc** [pathak22/noreward-rl#7]
Hi Deepak,

Thanks for sharing the code of your excellent work!
May I know the performance of your ```LSTMPolicy``` on RL benchmark like Atari Breakout?

James

**Comment by pathak22** [comment]
I am guessing, by this question, you are referring to vanilla-A3C which was adapted from [universe-starter-agent](https://github.com/openai/universe-starter-agent). You would have to train on atari with the relevant wrappers I have provided in `env_wrapper.py`. I guess I was able to achieve similar performance as A3C paper corresponding to unshared-RMSprop with similar hyper-parameters used in the A3C paper.

**Comment by pathak22** [comment]
Closing this issue as of now. Feel free to reopen if needed!
