### ISSUE TITLE
Does temporal autoencoder improve performance/speed?

### ISSUE THREAD

**Issue by ethancaballero** [pathak22/noreward-rl#8]
https://github.com/pathak22/noreward-rl/blob/master/src/model.py#L49-L111

I didn't see it mentioned in paper.

**Comment by pathak22** [comment]
Hello @ethancaballero, It is a new baseline I added in the camera ready version of paper.  I am going to update the arXiv in a week (i.e. before ICML 2017) to mention the result. It does not work as well as the ICM model, and is a bit slower too. More details to appear soon  in the updated arXiv. Thanks for pointing it out!

PS: closing this issue assuming this answered your question. Feel free to open, if you need.

**Comment by ethancaballero** [comment]
@pathak22 Did you try using temporal autoencoder and ICM at the same time? Does using both of them work better than using either of them individually?
